IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'BUAT_DUPLIKASI')
BEGIN
    DROP PROC BUAT_DUPLIKASI
END
GO
create proc BUAT_DUPLIKASI
AS
begin
select * into CC_BUMI FROM DAT_OP_BUMI 
SELECT * INTO CC_BANGUNAN FROM DAT_OP_BANGUNAN 
SELECT * INTO CC_OBJEK FROM DAT_OBJEK_PAJAK
SELECT * INTO CC_INDIVIDU FROM DAT_NILAI_INDIVIDU
SELECT * INTO CC_ZNT FROM DAT_ZNT
SELECT * INTO CC_FASILITAS FROM DAT_FASILITAS_BANGUNAN
SELECT * INTO CC_NJOPTKP FROM DAT_SUBJEK_PAJAK_NJOPTKP
SELECT * INTO CC2 FROM DAT_JPB2
SELECT * INTO CC3 FROM DAT_JPB3
SELECT * INTO CC4 FROM DAT_JPB4
SELECT * INTO CC5 FROM DAT_JPB5
SELECT * INTO CC6 FROM DAT_JPB6
SELECT * INTO CC7 FROM DAT_JPB7
SELECT * INTO CC8 FROM DAT_JPB8 
SELECT * INTO CC9 FROM DAT_JPB9 
SELECT * INTO CC12 FROM DAT_JPB12 
SELECT * INTO CC13 FROM DAT_JPB13
SELECT * INTO CC14 FROM DAT_JPB14
SELECT * INTO CC15 FROM DAT_JPB15
SELECT * INTO CC16 FROM DAT_JPB16
SELECT * INTO CC17 FROM DAT_JPB17
SELECT * INTO DBKB_1 FROM DBKB_DAYA_DUKUNG 
SELECT * INTO DBKB_2 FROM DBKB_MATERIAL 
SELECT * INTO DBKB_3 FROM DBKB_MEZANIN 
SELECT * INTO DBKB_4 FROM DBKB_STANDARD 
SELECT * INTO D1 FROM DBKB_JPB2
SELECT * INTO D2 FROM DBKB_JPB3
SELECT * INTO D3 FROM DBKB_JPB4
SELECT * INTO D4 FROM DBKB_JPB5
SELECT * INTO D5 FROM DBKB_JPB6
SELECT * INTO D6 FROM DBKB_JPB7
SELECT * INTO D7 FROM DBKB_JPB8
SELECT * INTO D8 FROM DBKB_JPB9
SELECT * INTO D9 FROM DBKB_JPB12
SELECT * INTO D10 FROM DBKB_JPB13
SELECT * INTO D11 FROM DBKB_JPB14
SELECT * INTO D12 FROM DBKB_JPB15
SELECT * INTO D13 FROM DBKB_JPB16
SELECT * INTO D14 FROM DBKB_JPB17
SELECT * INTO XNIR FROM DAT_NIR 
IF @@ERROR <>0 
BEGIN
ROLLBACK TRAN
END
ELSE
BEGIN
COMMIT TRAN
END
end
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'HAPUS_DUPLIKASI')
BEGIN
    DROP PROC HAPUS_DUPLIKASI
END
GO
CREATE PROC HAPUS_DUPLIKASI
AS
BEGIN
DELETE  from CC_BUMI
INSERT INTO CC_BUMI SELECT * FROM DAT_OP_BUMI 
DELETE  FROM CC_BANGUNAN
INSERT INTO CC_BANGUNAN SELECT * FROM DAT_OP_BANGUNAN
DELETE  FROM CC_OBJEK 
INSERT INTO CC_OBJEK SELECT * FROM DAT_OBJEK_PAJAK
DELETE  FROM CC_INDIVIDU
INSERT INTO CC_INDIVIDU SELECT * FROM DAT_NILAI_INDIVIDU 
DELETE  FROM CC_ZNT
INSERT INTO CC_ZNT SELECT * FROM DAT_ZNT
DELETE  FROM  CC_FASILITAS 
INSERT INTO CC_FASILITAS SELECT * FROM DAT_FASILITAS_BANGUNAN
DELETE  FROM CC_NJOPTKP
INSERT INTO CC_NJOPTKP SELECT * FROM DAT_SUBJEK_PAJAK_NJOPTKP
DELETE  From  CC2 
DELETE  From  CC3
DELETE  From  CC4
DELETE  From  CC5
DELETE  From  CC6
DELETE  From  CC7 
DELETE  From  CC8 
DELETE  From  CC9 
DELETE  From  CC12
DELETE  From  CC13 
DELETE  From  CC14 
DELETE  From  CC15 
DELETE  From  CC16 
DELETE  From  CC17 
        INSERT INTO CC2 select * FROM DAT_JPB2
        INSERT INTO CC3 select * FROM DAT_JPB3
        INSERT INTO CC4 select * FROM DAT_JPB4
        INSERT INTO CC5 select * FROM DAT_JPB5
        INSERT INTO CC6 select * FROM DAT_JPB6
        INSERT INTO CC7 select * FROM DAT_JPB7
        INSERT INTO CC8 select * FROM DAT_JPB8
        INSERT INTO CC9 select * FROM DAT_JPB9
        INSERT INTO CC12 select * FROM DAT_JPB12
        INSERT INTO CC13 select * FROM DAT_JPB13
        INSERT INTO CC14 select * FROM DAT_JPB14
        INSERT INTO CC15 select * FROM DAT_JPB15
        INSERT INTO CC16 select * FROM DAT_JPB16
        INSERT INTO CC17 select * FROM DAT_JPB17
      
DELETE FROM DBKB_1 
DELETE FROM DBKB_2 
DELETE FROM DBKB_3 
DELETE FROM DBKB_4 
DELETE FROM D1 
DELETE FROM D2 
DELETE FROM D3 
DELETE FROM D4 
DELETE FROM D5 
DELETE FROM D6 
DELETE FROM D7 
DELETE FROM D8 
DELETE FROM D9 
DELETE FROM D10 
DELETE FROM D11
DELETE FROM D12
DELETE FROM D13
DELETE FROM D14
DELETE FROM XNIR
INSERT INTO DBKB_1 select * FROM DBKB_DAYA_DUKUNG 
INSERT INTO DBKB_2 select * FROM DBKB_MATERIAL 
INSERT INTO DBKB_3 select * FROM DBKB_MEZANIN 
INSERT INTO DBKB_4 select * FROM DBKB_STANDARD 
INSERT INTO D1 select * FROM DBKB_JPB2
INSERT INTO D2 select * FROM DBKB_JPB3
INSERT INTO D3 select * FROM DBKB_JPB4
INSERT INTO D4 select * FROM DBKB_JPB5
INSERT INTO D5 select * FROM DBKB_JPB6
INSERT INTO D6 select * FROM DBKB_JPB7
INSERT INTO D7 select * FROM DBKB_JPB8
INSERT INTO D8 select * FROM DBKB_JPB9
INSERT INTO D9 select * FROM DBKB_JPB12
INSERT INTO D10 select * FROM DBKB_JPB13
INSERT INTO D11 select * FROM DBKB_JPB14
INSERT INTO D12 select * FROM DBKB_JPB15
INSERT INTO D13 select * FROM DBKB_JPB16
INSERT INTO D14 select * FROM DBKB_JPB17
INSERT INTO XNIR select * FROM DAT_NIR 

IF @@ERROR<>0
BEGIN
ROLLBACK TRAN
END
ELSE
BEGIN
COMMIT TRAN
END
END

GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'PULIH_DUPLIKASI')
BEGIN
    DROP PROC PULIH_DUPLIKASI
END
GO
CREATE PROC PULIH_DUPLIKASI
AS
BEGIN
DELETE  from DAT_OP_BUMI
INSERT INTO DAT_OP_BUMI SELECT * FROM CC_BUMI
DELETE  FROM DAT_OP_BANGUNAN
INSERT INTO DAT_OP_BANGUNAN SELECT * FROM CC_BANGUNAN
DELETE  FROM DAT_OBJEK_PAJAK
INSERT INTO DAT_OBJEK_PAJAK SELECT * FROM CC_OBJEK 
DELETE  FROM DAT_NILAI_INDIVIDU
INSERT INTO DAT_NILAI_INDIVIDU SELECT * FROM CC_INDIVIDU 
DELETE  FROM DAT_ZNT
INSERT INTO DAT_ZNT SELECT * FROM CC_ZNT
DELETE  FROM DAT_FASILITAS_BANGUNAN
INSERT INTO DAT_FASILITAS_BANGUNAN SELECT * FROM CC_FASILITAS 
DELETE  FROM DAT_SUBJEK_PAJAK_NJOPTKP
INSERT INTO DAT_SUBJEK_PAJAK_NJOPTKP SELECT * FROM CC_NJOPTKP
DELETE  From  DAT_JPB2 
DELETE  From  DAT_JPB3
DELETE  From  DAT_JPB4
DELETE  From  DAT_JPB5 
DELETE  From  DAT_JPB6 
DELETE  From  DAT_JPB7 
DELETE  From  DAT_JPB8 
DELETE  From  DAT_JPB9 
DELETE  From  DAT_JPB12 
DELETE  From  DAT_JPB13 
DELETE  From  DAT_JPB14 
DELETE  From  DAT_JPB15
DELETE  From  DAT_JPB16 
DELETE  From  DAT_JPB17
INSERT  INTO DAT_JPB2 SELECT * FROM CC2
INSERT  INTO DAT_JPB3 SELECT * FROM CC3
INSERT  INTO DAT_JPB4 SELECT * FROM CC4
INSERT  INTO DAT_JPB5 SELECT * FROM CC5
INSERT  INTO DAT_JPB6 SELECT * FROM CC6
INSERT  INTO DAT_JPB7 SELECT * FROM CC7
INSERT  INTO DAT_JPB8 SELECT * FROM CC8
INSERT  INTO DAT_JPB9 SELECT * FROM CC9
INSERT  INTO DAT_JPB12 SELECT * FROM CC12
INSERT  INTO DAT_JPB13 SELECT * FROM CC13
INSERT  INTO DAT_JPB14 SELECT * FROM CC14
INSERT  INTO DAT_JPB15 SELECT * FROM CC15
INSERT  INTO DAT_JPB16 SELECT * FROM CC16
INSERT  INTO DAT_JPB17 SELECT * FROM CC17

DELETE FROM DBKB_DAYA_DUKUNG 
DELETE FROM DBKB_MATERIAL 
DELETE FROM DBKB_MEZANIN 
DELETE FROM DBKB_STANDARD 
DELETE FROM DBKB_JPB2
DELETE FROM DBKB_JPB3
DELETE FROM DBKB_JPB4
DELETE FROM DBKB_JPB5
DELETE FROM DBKB_JPB6
DELETE FROM DBKB_JPB7
DELETE FROM DBKB_JPB8
DELETE FROM DBKB_JPB9
DELETE FROM DBKB_JPB12
DELETE FROM DBKB_JPB13
DELETE FROM DBKB_JPB14
DELETE FROM DBKB_JPB15
DELETE FROM DBKB_JPB16
DELETE FROM DBKB_JPB17

INSERT INTO DBKB_DAYA_DUKUNG select * FROM  DBKB_1 
INSERT INTO DBKB_MATERIAL select * FROM DBKB_2 
INSERT INTO DBKB_MEZANIN select * FROM DBKB_3 
INSERT INTO DBKB_STANDARD select * FROM DBKB_4 
INSERT INTO DBKB_JPB2 select * FROM D1
INSERT INTO DBKB_JPB3 select * FROM D2
INSERT INTO DBKB_JPB4 select * FROM D3
INSERT INTO DBKB_JPB5 select * FROM D4
INSERT INTO DBKB_JPB6 select * FROM D5
INSERT INTO DBKB_JPB7 select * FROM D6
INSERT INTO DBKB_JPB8 select * FROM D7
INSERT INTO DBKB_JPB9 select * FROM D8
INSERT INTO DBKB_JPB12 select * FROM D9
INSERT INTO DBKB_JPB13 select * FROM D10
INSERT INTO DBKB_JPB14 select * FROM D11
INSERT INTO DBKB_JPB15 select * FROM D12
INSERT INTO DBKB_JPB16 select * FROM D13
INSERT INTO DBKB_JPB17 select * FROM D14
DELETE FROM DAT_NIR
INSERT INTO DAT_NIR select * FROM XNIR
IF @@ERROR<>0 
BEGIN
ROLLBACK TRAN
END
ELSE
BEGIN
COMMIT TRAN
END
END