USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'HITUNG_DBKB_JPB8')
BEGIN
    DROP PROC HITUNG_DBKB_JPB8
END
GO
create PROCEDURE HITUNG_DBKB_JPB8
@VLC_THN_HRG_PEKERJAAN_JPB8 NVARCHAR(4)
AS
BEGIN                           
  DECLARE @VLC_KD_PEKERJAAN             NVARCHAR(2),
  @VLC_KD_KEGIATAN              NVARCHAR(2),
  @VLN_LBR_BENT_MIN_HRG_JPB8    INT,
  @VLN_LBR_BENT_MAX_HRG_JPB8    INT,
  @VLN_TING_KOLOM_MIN_HRG_JPB8  INT,
  @VLN_TING_KOLOM_MAX_HRG_JPB8  INT,
  @VLN_FAKTOR_PEMBAGI_TIPE_BNG  INT,
  @VLN_HRG_DBKB_JPB8            FLOAT--NUMERIC(12,2),
  @VLN_HRG_DBKB_JPB8_AKHIR      FLOAT--NUMERIC(12,2),
  @VCEK                         NVARCHAR(2)
  DECLARE C_PEK_KEG_JPB8 CURSOR FOR
  SELECT DISTINCT KD_PEKERJAAN,KD_KEGIATAN,LBR_BENT_MIN_HRG_JPB8,LBR_BENT_MAX_HRG_JPB8,TING_KOLOM_MIN_HRG_JPB8,TING_KOLOM_MAX_HRG_JPB8
  FROM HRG_KEGIATAN_JPB8 WHERE KD_PROPINSI =  '12' AND KD_DATI2    =  '12' AND THN_HRG_PEKERJAAN_JPB8 =	@VLC_THN_HRG_PEKERJAAN_JPB8
  OPEN C_PEK_KEG_JPB8
  FETCH C_PEK_KEG_JPB8 INTO @VLC_KD_PEKERJAAN,
	   @VLC_KD_KEGIATAN, @VLN_LBR_BENT_MIN_HRG_JPB8,
	   @VLN_LBR_BENT_MAX_HRG_JPB8,@VLN_TING_KOLOM_MIN_HRG_JPB8,@VLN_TING_KOLOM_MAX_HRG_JPB8
WHILE @@FETCH_STATUS =0
BEGIN
   SELECT @VLN_FAKTOR_PEMBAGI_TIPE_BNG=FAKTOR_PEMBAGI_TIPE_BNG FROM TIPE_BANGUNAN
   WHERE LUAS_MIN_TIPE_BNG = @VLN_LBR_BENT_MIN_HRG_JPB8 AND
         LUAS_MAX_TIPE_BNG = @VLN_LBR_BENT_MAX_HRG_JPB8

   SELECT @VLN_HRG_DBKB_JPB8=SUM(HRG_KEGIATAN_JPB8) FROM HRG_KEGIATAN_JPB8
   WHERE KD_PROPINSI             = '12' AND
         KD_DATI2                = '12' AND
         THN_HRG_PEKERJAAN_JPB8  = @VLC_THN_HRG_PEKERJAAN_JPB8      AND
         LBR_BENT_MIN_HRG_JPB8   = @VLN_LBR_BENT_MIN_HRG_JPB8   AND
         LBR_BENT_MAX_HRG_JPB8   = @VLN_LBR_BENT_MAX_HRG_JPB8   AND
         TING_KOLOM_MIN_HRG_JPB8 = @VLN_TING_KOLOM_MIN_HRG_JPB8 AND
         TING_KOLOM_MAX_HRG_JPB8 = @VLN_TING_KOLOM_MAX_HRG_JPB8

   SET @VLN_HRG_DBKB_JPB8_AKHIR = (@VLN_HRG_DBKB_JPB8) /(@VLN_FAKTOR_PEMBAGI_TIPE_BNG)

   --BEGIN
	   SELECT @VCEK=KD_PROPINSI FROM DBKB_JPB8
	   WHERE KD_PROPINSI              = '12' AND
	         KD_DATI2                 = '12' AND
	         THN_DBKB_JPB8            = @VLC_THN_HRG_PEKERJAAN_JPB8  AND
	         LBR_BENT_MIN_DBKB_JPB8   = @VLN_LBR_BENT_MIN_HRG_JPB8   AND
	         LBR_BENT_MAX_DBKB_JPB8   = @VLN_LBR_BENT_MAX_HRG_JPB8   AND
	         TING_KOLOM_MIN_DBKB_JPB8 = @VLN_TING_KOLOM_MIN_HRG_JPB8 AND
	         TING_KOLOM_MAX_DBKB_JPB8 = @VLN_TING_KOLOM_MAX_HRG_JPB8
--   EXCEPTION
  --     WHEN NO_DATA_FOUND THEN
    IF @VCEK IS NULL
	BEGIN
	   SET @VCEK = 'TT'
	END

   IF @VCEK <> 'TT' 
   BEGIN
      UPDATE DBKB_JPB8 SET NILAI_DBKB_JPB8            = @VLN_HRG_DBKB_JPB8_AKHIR
      WHERE KD_PROPINSI              = '12' AND
	        KD_DATI2                 = '12' AND
            THN_DBKB_JPB8            = @VLC_THN_HRG_PEKERJAAN_JPB8  AND
            LBR_BENT_MIN_DBKB_JPB8   = @VLN_LBR_BENT_MIN_HRG_JPB8   AND
            LBR_BENT_MAX_DBKB_JPB8   = @VLN_LBR_BENT_MAX_HRG_JPB8   AND
            TING_KOLOM_MIN_DBKB_JPB8 = @VLN_TING_KOLOM_MIN_HRG_JPB8 AND
            TING_KOLOM_MAX_DBKB_JPB8 = @VLN_TING_KOLOM_MAX_HRG_JPB8
   END
   ELSE
   BEGIN
      INSERT INTO DBKB_JPB8(KD_PROPINSI,KD_DATI2,THN_DBKB_JPB8,LBR_BENT_MIN_DBKB_JPB8,LBR_BENT_MAX_DBKB_JPB8,
		  TING_KOLOM_MIN_DBKB_JPB8,TING_KOLOM_MAX_DBKB_JPB8,NILAI_DBKB_JPB8)
      VALUES('12','12',@VLC_THN_HRG_PEKERJAAN_JPB8,@VLN_LBR_BENT_MIN_HRG_JPB8,@VLN_LBR_BENT_MAX_HRG_JPB8,
		  @VLN_TING_KOLOM_MIN_HRG_JPB8,@VLN_TING_KOLOM_MAX_HRG_JPB8,@VLN_HRG_DBKB_JPB8_AKHIR)
   END 
   FETCH NEXT FROM C_PEK_KEG_JPB8 INTO @VLC_KD_PEKERJAAN,
	   @VLC_KD_KEGIATAN, @VLN_LBR_BENT_MIN_HRG_JPB8,
	   @VLN_LBR_BENT_MAX_HRG_JPB8,@VLN_TING_KOLOM_MIN_HRG_JPB8,@VLN_TING_KOLOM_MAX_HRG_JPB8
END
   CLOSE C_PEK_KEG_JPB8
   DEALLOCATE C_PEK_KEG_JPB8
  
if @@ERROR<>0 
begin
rollback tran
end
else
begin
commit tran
end
END
