USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'LUNAS_MASSAL')
BEGIN
    DROP PROC LUNAS_MASSAL
END
GO
CREATE proc LUNAS_MASSAL
@xxKec nVarchar(3), @xxKel nVarchar(3),
@xTahun nvarchar(4),@xTP nvarchar(2),
@xDenda float,@TBayar datetime, @TRekam datetime, @xNIP nvarchar(30),
@xProses nvarchar(1)
 
AS
BEGIN

Declare @xBayar float
Declare @xProp nVarchar(2), @xKab nVarchar(2),@xKec nVarchar(3), @xKel nVarchar(3),@Tahun nVarchar(4),
@xBlok nVarchar(3), @xUrut nVarchar(4), @xJenis nVarchar(1)--,@BayarKe smallint

if @xProses = '1'
begin
DELETE  From PEMBAYARAN_SPPT WHERE THN_PAJAK_SPPT=@xTahun
	DECLARE C_LUNAS CURSOR FOR 
	SELECT KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PBB_YG_HARUS_DIBAYAR_SPPT 
	FROM SPPT WHERE THN_PAJAK_SPPT=@xTahun
	OPEN C_LUNAS 
	FETCH FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	WHILE @@FETCH_STATUS = 0
	BEGIN		
		INSERT INTO PEMBAYARAN_SPPT(KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PEMBAYARAN_SPPT_KE,KD_KANWIL_BANK, KD_KPPBB_BANK,KD_BANK_TUNGGAL,KD_BANK_PERSEPSI,KD_TP,DENDA_SPPT,JML_SPPT_YG_DIBAYAR,TGL_PEMBAYARAN_SPPT,TGL_REKAM_BYR_SPPT,NIP_REKAM_BYR_SPPT)
			values (@xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @xTahun,1,'01', '16','01','01', @xTP,@xDenda,@xBayar+@xDenda,@TBayar,@TRekam,@xNIP) 	
		FETCH NEXT FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	END
	CLOSE C_LUNAS
	DEALLOCATE C_LUNAS
	UPDATE SPPT SET STATUS_PEMBAYARAN_SPPT ='1' WHERE THN_PAJAK_SPPT=@xTahun 
end
else
if @xProses = '2'
begin
DELETE  From PEMBAYARAN_SPPT WHERE KD_KECAMATAN=@xxKec and THN_PAJAK_SPPT=@xTahun
	DECLARE C_LUNAS CURSOR FOR 
	SELECT KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PBB_YG_HARUS_DIBAYAR_SPPT 
	FROM SPPT WHERE KD_KECAMATAN=@xxKec and THN_PAJAK_SPPT=@xTahun
	OPEN C_LUNAS 
	FETCH FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	WHILE @@FETCH_STATUS = 0
	BEGIN		
		INSERT INTO PEMBAYARAN_SPPT(KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PEMBAYARAN_SPPT_KE,KD_KANWIL_BANK, KD_KPPBB_BANK,KD_BANK_TUNGGAL,KD_BANK_PERSEPSI,KD_TP,DENDA_SPPT,JML_SPPT_YG_DIBAYAR,TGL_PEMBAYARAN_SPPT,TGL_REKAM_BYR_SPPT,NIP_REKAM_BYR_SPPT)
			values (@xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @xTahun,1,'01', '16','01','01', @xTP,@xDenda,@xBayar+@xDenda,@TBayar,@TRekam,@xNIP) 	
		FETCH NEXT FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	END
	CLOSE C_LUNAS
	DEALLOCATE C_LUNAS
	UPDATE SPPT SET STATUS_PEMBAYARAN_SPPT ='1' WHERE KD_KECAMATAN=@xxKec and THN_PAJAK_SPPT=@xTahun 
end
else
if @xProses = '3'
begin
	DELETE  From PEMBAYARAN_SPPT WHERE KD_KECAMATAN=@xxKec and KD_KELURAHAN=@xxKel and THN_PAJAK_SPPT=@xTahun
	DECLARE C_LUNAS CURSOR FOR 
	SELECT KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PBB_YG_HARUS_DIBAYAR_SPPT 
	FROM SPPT WHERE KD_KECAMATAN=@xxKec and KD_KELURAHAN=@xxKel and THN_PAJAK_SPPT=@xTahun
	OPEN C_LUNAS 
	FETCH FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	WHILE @@FETCH_STATUS = 0
	BEGIN		
		INSERT INTO PEMBAYARAN_SPPT(KD_PROPINSI,KD_DATI2,KD_KECAMATAN,KD_KELURAHAN,KD_BLOK,NO_URUT,KD_JNS_OP,THN_PAJAK_SPPT,PEMBAYARAN_SPPT_KE,KD_KANWIL_BANK, KD_KPPBB_BANK,KD_BANK_TUNGGAL,KD_BANK_PERSEPSI,KD_TP,DENDA_SPPT,JML_SPPT_YG_DIBAYAR,TGL_PEMBAYARAN_SPPT,TGL_REKAM_BYR_SPPT,NIP_REKAM_BYR_SPPT)
			values (@xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @xTahun,1,'01', '16','01','01', @xTP,@xDenda,@xBayar+@xDenda,@TBayar,@TRekam,@xNIP) 	
		FETCH NEXT FROM C_LUNAS INTO @xProp,@xKab,@xKec,@xKel,@xBlok,@xUrut,@xJenis, @Tahun,@xBayar
	END
	CLOSE C_LUNAS
	DEALLOCATE C_LUNAS
	UPDATE SPPT SET STATUS_PEMBAYARAN_SPPT ='1' WHERE KD_KECAMATAN=@xxKec and KD_KELURAHAN =@xxKel and THN_PAJAK_SPPT=@xTahun 
end


if @@ERROR<>0 
begin
rollback tran
end
else
begin
commit tran
end
end		
    