USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'TOT_DBKB_STANDARD')
BEGIN
    DROP PROC TOT_DBKB_STANDARD
END
GO
CREATE PROCEDURE TOT_DBKB_STANDARD
@xTahun NVARCHAR(4)
AS
BEGIN
	BEGIN
		EXEC H_SATUAN @xTahun
	END
	BEGIN
		EXEC H_KEGIATAN @xTahun
	END
	BEGIN
		EXEC HITUNG_DBKB_STANDARD @xTahun
	END
	BEGIN
		EXEC HITUNG_DBKB_FINAL @xTahun
	END
END