CREATE PROC DELETE_BUMI
@xNOP nvarchar(30),@xNOP1 nvarchar(30)
AS
BEGIN
DELETE FROM DAT_OP_BUMI WHERE ('12.12.' + KD_KECAMATAN + '.' + KD_KELURAHAN+ '.' + KD_BLOK + '-' + NO_URUT + '.' + KD_JNS_OP)=@xNOP
DELETE FROM DAT_OBJEK_PAJAK WHERE ('12.12.' + KD_KECAMATAN + '.' + KD_KELURAHAN+ '.' + KD_BLOK + '-' + NO_URUT + '.' + KD_JNS_OP)=@xNOP1
IF @@ERROR<>0 
BEGIN
ROLLBACK TRAN
END
ELSE
BEGIN
COMMIT TRAN
END
END