USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'HITUNG_DBKB_STANDARD')
BEGIN
    DROP PROC HITUNG_DBKB_STANDARD
END
GO
CREATE PROCEDURE HITUNG_DBKB_STANDARD
@VLC_THN_DBKB_STANDARD NVARCHAR(4)
AS
BEGIN  
  DECLARE   @VLC_KD_JPB                  NVARCHAR(2),
  @VLC_TIPE_BNG                NVARCHAR(5),
  @VLC_KD_BNG_LANTAI           NVARCHAR(8),
  @VLN_DBKB_STANDARD1_1_314    FLOAT,
  @VLN_DBKB_STANDARD1_1_656    FLOAT,
  @VLN_FAKTOR_PEMBAGI1_1_314   FLOAT,
  @VLN_FAKTOR_PEMBAGI1_1_656   FLOAT,
  @VLN_DBKB_STANDARD_A1_1_314  FLOAT,
  @VLN_DBKB_STANDARD_A1_1_656  FLOAT,
  @VLN_DBKB_STANDARD_A1_1_500  FLOAT,
  @VLN_DBKB_STANDARD1_2_257    FLOAT,
  @VLN_DBKB_STANDARD1_2_474    FLOAT,
  @VLN_FAKTOR_PEMBAGI1_2_257   FLOAT,
  @VLN_FAKTOR_PEMBAGI1_2_474   FLOAT,
  @VLN_DBKB_STANDARD_A1_2_257  FLOAT,
  @VLN_DBKB_STANDARD_A1_2_474  FLOAT,
  @VLN_DBKB_STANDARD_A1_2_375  FLOAT,
  @VLN_DBKB_STANDARD           FLOAT,
  @VLN_NILAI                   BIGINT,
  @VLN_FAKTOR_PEMBAGI          FLOAT,
  @VLN_DBKB_STANDARD_AKHIR     FLOAT
  DECLARE  C_JPB_TIPEBNG_BNG_LANTAI CURSOR FOR
  SELECT DISTINCT KD_JPB,TIPE_BNG,KD_BNG_LANTAI FROM BANGUNAN_LANTAI WHERE KD_JPB IN('01','02','05')
  OPEN C_JPB_TIPEBNG_BNG_LANTAI
  FETCH C_JPB_TIPEBNG_BNG_LANTAI  INTO  @VLC_KD_JPB,@VLC_TIPE_BNG,@VLC_KD_BNG_LANTAI
  WHILE @@FETCH_STATUS=0
  BEGIN
  
  /*------------------------------------------------------
  JIKA BANGUNAN YANG PUNYA KODE BANGUNAN LANTAI = 1_1_500
  -------------------------------------------------------*/
  IF RTRIM(LTRIM(@VLC_KD_BNG_LANTAI)) = '1_1_500' 
  BEGIN

	--AMBIL NILAI DBKB STANDARD DARI JUMLAH HARGA KEGIATAN
	--UNTUK KODE BANGUNAN LANTAI = 1_1_314
    SELECT @VLN_DBKB_STANDARD1_1_314=SUM(HRG_KEGIATAN) FROM HRG_KEGIATAN
    WHERE KD_PROPINSI                 = '12'     AND
	      KD_DATI2                    = '12' AND
          THN_KEGIATAN                = @VLC_THN_DBKB_STANDARD AND
		  RTRIM(LTRIM(KD_JPB))        = '01'                  AND
          RTRIM(LTRIM(TIPE_BNG))      = '314'                 AND
		  RTRIM(LTRIM(KD_BNG_LANTAI)) = '1_1_314'

	--AMBIL NILAI DBKB STANDARD DARI JUMLAH HARGA KEGIATAN
	--UNTUK KODE BANGUNAN LANTAI = 1_1_656
    SELECT @VLN_DBKB_STANDARD1_1_656=SUM(HRG_KEGIATAN)FROM HRG_KEGIATAN
    WHERE KD_PROPINSI                 = '12' AND
	      KD_DATI2                    = '12' AND
          THN_KEGIATAN                = @VLC_THN_DBKB_STANDARD AND
		  RTRIM(LTRIM(KD_JPB))        = '01'                  AND
          LTRIM(RTRIM(TIPE_BNG))      = '656'                 AND
		  LTRIM(RTRIM(KD_BNG_LANTAI)) = '1_1_656'

	--AMBIL FAKTOR PEMBAGI UNTUK KODE BANGUNAN LANTAI = 1_1_314
    SELECT @VLN_FAKTOR_PEMBAGI1_1_314=FAKTOR_PEMBAGI_TIPE_BNG FROM TIPE_BANGUNAN
    WHERE LTRIM(RTRIM(TIPE_BNG)) ='314'
	IF @VLN_FAKTOR_PEMBAGI1_1_314 IS NULL 
	BEGIN
	   SET @VLN_FAKTOR_PEMBAGI1_1_314 = 1
	END

	--AMBIL FAKTOR PEMBAGI UNTUK KODE BANGUNAN LANTAI = 1_1_656
    SELECT @VLN_FAKTOR_PEMBAGI1_1_656=FAKTOR_PEMBAGI_TIPE_BNG FROM TIPE_BANGUNAN
    WHERE LTRIM(RTRIM(TIPE_BNG)) ='656'
	IF @VLN_FAKTOR_PEMBAGI1_1_656 IS NULL 
	BEGIN
	   SET @VLN_FAKTOR_PEMBAGI1_1_656 = 1
	END 

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_1_314
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_1_314 = round(round(@VLN_DBKB_STANDARD1_1_314,2)/round(@VLN_FAKTOR_PEMBAGI1_1_314,2),2)

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_1_656
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_1_656 = round(round(@VLN_DBKB_STANDARD1_1_656,2)/round(@VLN_FAKTOR_PEMBAGI1_1_656,2),2)

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_1_5000
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_1_500 = @VLN_DBKB_STANDARD_A1_1_314+(0.543859649*(@VLN_DBKB_STANDARD_A1_1_656-@VLN_DBKB_STANDARD_A1_1_314))
    --@VLN_DBKB_STANDARD_A1_1_314+((500-314)/(656-314)*(@VLN_DBKB_STANDARD_A1_1_656-@VLN_DBKB_STANDARD_A1_1_314))

	SELECT @VLN_NILAI=COUNT(*) FROM DBKB_STANDARD
    WHERE KD_PROPINSI       = '12' AND
	      KD_DATI2          = '12' AND
          THN_DBKB_STANDARD = @VLC_THN_DBKB_STANDARD AND
		  KD_JPB            = @VLC_KD_JPB            AND
          TIPE_BNG          = @VLC_TIPE_BNG          AND
		  KD_BNG_LANTAI     = @VLC_KD_BNG_LANTAI
    IF @VLN_NILAI = 0 
    BEGIN
       INSERT INTO DBKB_STANDARD(KD_PROPINSI,KD_DATI2,THN_DBKB_STANDARD,KD_JPB,TIPE_BNG,KD_BNG_LANTAI,NILAI_DBKB_STANDARD)
		VALUES ('12','12',@VLC_THN_DBKB_STANDARD,'01','500','1_1_500',@VLN_DBKB_STANDARD_A1_1_500)
	END
	ELSE
	BEGIN
       UPDATE DBKB_STANDARD SET NILAI_DBKB_STANDARD=@VLN_DBKB_STANDARD_A1_1_500
       WHERE KD_PROPINSI                 = '12' AND
	         KD_DATI2                    = '12' AND
             THN_DBKB_STANDARD           = @VLC_THN_DBKB_STANDARD AND
			 RTRIM(LTRIM(KD_JPB))        = '01'                  AND
             RTRIM(LTRIM(TIPE_BNG))      = '500'                 AND
			 RTRIM(LTRIM(KD_BNG_LANTAI)) = '1_1_500'
    END
  END

  /*-----------------------------------------------------
  JIKA BANGUNAN YANG PUNYA KODE BANGUNAN LANTAI = 1_2_375
  -----------------------------------------------------*/
  ELSE IF RTRIM(LTRIM(@VLC_KD_BNG_LANTAI)) = '1_2_375' 
  BEGIN

    --AMBIL NILAI DBKB STANDARD DARI JUMLAH HARGA KEGIATAN
	--UNTUK KODE BANGUNAN LANTAI = 1_2_257
    SELECT @VLN_DBKB_STANDARD1_2_257=SUM(HRG_KEGIATAN) FROM HRG_KEGIATAN
    WHERE KD_PROPINSI                 = '12' AND
	      KD_DATI2                    = '12' AND
          THN_KEGIATAN                = @VLC_THN_DBKB_STANDARD AND
		  LTRIM(RTRIM(KD_JPB))        = '01'                  AND
          LTRIM(RTRIM(TIPE_BNG))      = '257'                 AND
		  LTRIM(RTRIM(KD_BNG_LANTAI)) = '1_2_257'

	--AMBIL NILAI DBKB STANDARD DARI JUMLAH HARGA KEGIATAN
	--UNTUK KODE BANGUNAN LANTAI = 1_2_474
    SELECT @VLN_DBKB_STANDARD1_2_474=SUM((HRG_KEGIATAN)) FROM HRG_KEGIATAN
    WHERE KD_PROPINSI                 = '12' AND
	      KD_DATI2                    = '12' AND
          THN_KEGIATAN                = @VLC_THN_DBKB_STANDARD AND
		  KD_JPB                      = '01'                  AND
          LTRIM(RTRIM(TIPE_BNG))      = '474'                 AND
		  LTRIM(RTRIM(KD_BNG_LANTAI)) = '1_2_474'

    --AMBIL FAKTOR PEMBAGI UNTUK KODE BANGUNAN LANTAI = 1_2_257
    SELECT @VLN_FAKTOR_PEMBAGI1_2_257=FAKTOR_PEMBAGI_TIPE_BNG FROM TIPE_BANGUNAN
    WHERE LTRIM(RTRIM(TIPE_BNG)) = '257'
	IF @VLN_FAKTOR_PEMBAGI1_2_257 IS NULL 
	BEGIN
	   SET @VLN_FAKTOR_PEMBAGI1_2_257 = 1
	END 

	--AMBIL FAKTOR PEMBAGI UNTUK KODE BANGUNAN LANTAI = 1_2_474
    SELECT @VLN_FAKTOR_PEMBAGI1_2_474=FAKTOR_PEMBAGI_TIPE_BNG FROM TIPE_BANGUNAN
    WHERE LTRIM(RTRIM(TIPE_BNG)) = '474'
	IF @VLN_FAKTOR_PEMBAGI1_2_474 IS NULL 
	BEGIN
	   SET @VLN_FAKTOR_PEMBAGI1_2_474 = 1 
	END

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_2_257
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_2_257 = @VLN_DBKB_STANDARD1_2_257/@VLN_FAKTOR_PEMBAGI1_2_257

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_2_474
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_2_474 = @VLN_DBKB_STANDARD1_2_474/@VLN_FAKTOR_PEMBAGI1_2_474

	--NILAI DBKB STANDAR BANGUNAN UNTUK KODE BANGUNAN LANTAI = 1_2_375
	--SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_A1_2_375 = @VLN_DBKB_STANDARD_A1_2_257+(0.543778802*(@VLN_DBKB_STANDARD_A1_2_474-@VLN_DBKB_STANDARD_A1_2_257))
    --@VLN_DBKB_STANDARD_A1_2_257+((375-257)/(474-257)*(@VLN_DBKB_STANDARD_A1_2_474-@VLN_DBKB_STANDARD_A1_2_257))

	SELECT @VLN_NILAI=COUNT(*) FROM DBKB_STANDARD
    WHERE KD_PROPINSI       = '12' AND
	      KD_DATI2          = '12' AND
          THN_DBKB_STANDARD = @VLC_THN_DBKB_STANDARD AND
		  KD_JPB            = @VLC_KD_JPB            AND
          TIPE_BNG          = @VLC_TIPE_BNG          AND
		  KD_BNG_LANTAI     = @VLC_KD_BNG_LANTAI
    IF @VLN_NILAI = 0 
    BEGIN
       INSERT INTO DBKB_STANDARD(KD_PROPINSI,KD_DATI2,THN_DBKB_STANDARD,KD_JPB,TIPE_BNG,KD_BNG_LANTAI,NILAI_DBKB_STANDARD)
       VALUES ('12','12',@VLC_THN_DBKB_STANDARD,'01','375','1_2_375',@VLN_DBKB_STANDARD_A1_2_375)
    END
	ELSE
	BEGIN
       UPDATE DBKB_STANDARD SET NILAI_DBKB_STANDARD=@VLN_DBKB_STANDARD_A1_2_375
       WHERE KD_PROPINSI                 = '12' AND
	         KD_DATI2                    = '12' AND
             THN_DBKB_STANDARD           = @VLC_THN_DBKB_STANDARD AND
			 RTRIM(LTRIM(KD_JPB))        = '01'                  AND
             RTRIM(LTRIM(TIPE_BNG))      = '375'                 AND
			 RTRIM(LTRIM(KD_BNG_LANTAI)) = '1_2_375'
    END
  END

  /*-------------------------------------------------------------------------
  JIKA BANGUNAN YANG PUNYA KODE BANGUNAN LANTAI SELAIN = 1_1_314 ATAU 1_2_375
  -------------------------------------------------------------------------*/
  ELSE
  BEGIN

	--AMBIL NILAI DBKB STANDARD DARI JUMLAH HARGA KEGIATAN (UMUM)
    SELECT @VLN_DBKB_STANDARD=SUM(HRG_KEGIATAN)
	FROM HRG_KEGIATAN
    WHERE KD_PROPINSI   = '12' AND
	      KD_DATI2      = '12' AND
          THN_KEGIATAN  = @VLC_THN_DBKB_STANDARD AND
		  KD_JPB        = @VLC_KD_JPB            AND
          TIPE_BNG      = @VLC_TIPE_BNG          AND
		  KD_BNG_LANTAI = @VLC_KD_BNG_LANTAI

	--AMBIL FAKTOR PEMBAGI
    SELECT @VLN_FAKTOR_PEMBAGI=FAKTOR_PEMBAGI_TIPE_BNG
    FROM TIPE_BANGUNAN WHERE TIPE_BNG = @VLC_TIPE_BNG
	IF @VLN_FAKTOR_PEMBAGI IS NULL 
	BEGIN
	   SET @VLN_FAKTOR_PEMBAGI = 1
	END 

	--NILAI DBKB STANDAR AKHIR SETELAH DIBAGI FAKTOR PEMBAGI
    SET @VLN_DBKB_STANDARD_AKHIR = (@VLN_DBKB_STANDARD/@VLN_FAKTOR_PEMBAGI)
	IF @VLN_DBKB_STANDARD_AKHIR IS NULL 
	BEGIN
	   SET @VLN_DBKB_STANDARD_AKHIR = 0
	END 

	SELECT @VLN_NILAI=COUNT(*) FROM DBKB_STANDARD
    WHERE KD_PROPINSI       = '12' AND
	      KD_DATI2          = '12' AND
          THN_DBKB_STANDARD = @VLC_THN_DBKB_STANDARD AND
		  KD_JPB            = @VLC_KD_JPB            AND
          TIPE_BNG          = @VLC_TIPE_BNG          AND
		  KD_BNG_LANTAI     = @VLC_KD_BNG_LANTAI
    IF @VLN_NILAI = 0 
    BEGIN
       INSERT INTO DBKB_STANDARD(KD_PROPINSI,KD_DATI2,THN_DBKB_STANDARD,KD_JPB,TIPE_BNG,KD_BNG_LANTAI,NILAI_DBKB_STANDARD)
       VALUES ('12','12',@VLC_THN_DBKB_STANDARD,@VLC_KD_JPB,@VLC_TIPE_BNG,@VLC_KD_BNG_LANTAI,@VLN_DBKB_STANDARD_AKHIR)
	END
    ELSE
    BEGIN
       UPDATE DBKB_STANDARD SET NILAI_DBKB_STANDARD = @VLN_DBKB_STANDARD_AKHIR
       WHERE KD_PROPINSI       = '12' AND
	         KD_DATI2          = '12' AND
             THN_DBKB_STANDARD = @VLC_THN_DBKB_STANDARD AND
			 KD_JPB            = @VLC_KD_JPB            AND
             TIPE_BNG          = @VLC_TIPE_BNG          AND
			 KD_BNG_LANTAI     = @VLC_KD_BNG_LANTAI
	END
  END
  FETCH NEXT FROM C_JPB_TIPEBNG_BNG_LANTAI INTO @VLC_KD_JPB,@VLC_TIPE_BNG,@VLC_KD_BNG_LANTAI
  END
  CLOSE C_JPB_TIPEBNG_BNG_LANTAI
  DEALLOCATE C_JPB_TIPEBNG_BNG_LANTAI
IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
END
ELSE
BEGIN
	COMMIT TRANSACTION
END  
END 
