USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'DBKB_MAT_HARGA_SATUAN')
BEGIN
    DROP PROC DBKB_MAT_HARGA_SATUAN
END
GO
CREATE PROCEDURE DBKB_MAT_HARGA_SATUAN
@VLC_MASUKAN_TAHUN NVARCHAR(4)
AS
BEGIN
    DECLARE @VLC_KD_PEKERJAAN NVARCHAR(2),
    @VLC_KD_KEGIATAN  NVARCHAR(2),
    @VLN_HRG_SATUAN   NUMERIC(12,4),
    @VLN_NILAI        BIGINT

	DECLARE C_PEK_KEG_X1 CURSOR FOR SELECT DISTINCT KD_PEKERJAAN, KD_KEGIATAN
    FROM VOL_RESOURCE WHERE KD_PEKERJAAN IN ('21','22','23','24')
--Hitung Harga Satuan
    OPEN C_PEK_KEG_X1
    FETCH C_PEK_KEG_X1 INTO @VLC_KD_PEKERJAAN,@VLC_KD_KEGIATAN
    WHILE @@FETCH_STATUS=0
    BEGIN
		SELECT @VLN_HRG_SATUAN=SUM(A.VOL_RESOURCE * B.HRG_RESOURCE)FROM VOL_RESOURCE A,HRG_RESOURCE B
		WHERE  A.KD_GROUP_RESOURCE = B.KD_GROUP_RESOURCE AND
			   A.KD_RESOURCE       = B.KD_RESOURCE       AND
			   A.KD_PEKERJAAN      = @VLC_KD_PEKERJAAN    AND
			   A.KD_KEGIATAN       = @VLC_KD_KEGIATAN     AND
			   B.KD_PROPINSI       = '12' AND
			   B.KD_DATI2          = '12' AND
			   B.THN_HRG_RESOURCE  = @VLC_MASUKAN_TAHUN

		SELECT @VLN_NILAI =COUNT(*)FROM HRG_SATUAN
		WHERE KD_PROPINSI    = '12' AND
			  KD_DATI2       = '12' AND
			  THN_HRG_SATUAN = @VLC_MASUKAN_TAHUN AND
			  KD_PEKERJAAN   = @VLC_KD_PEKERJAAN  AND
			  KD_KEGIATAN    = @VLC_KD_KEGIATAN 

		IF @VLN_NILAI= 0 
		BEGIN
		   INSERT INTO HRG_SATUAN (KD_PROPINSI,KD_DATI2,THN_HRG_SATUAN,KD_PEKERJAAN,KD_KEGIATAN,HRG_SATUAN)
		   VALUES('12','12',@VLC_MASUKAN_TAHUN,@VLC_KD_PEKERJAAN,@VLC_KD_KEGIATAN,@VLN_HRG_SATUAN)
		END
		ELSE
		BEGIN
		   UPDATE HRG_SATUAN SET HRG_SATUAN     = @VLN_HRG_SATUAN
		   WHERE KD_PROPINSI  = '12' AND
			   KD_DATI2       = '12' AND
			   THN_HRG_SATUAN = @VLC_MASUKAN_TAHUN AND
			   KD_PEKERJAAN   = @VLC_KD_PEKERJAAN AND
			   KD_KEGIATAN    = @VLC_KD_KEGIATAN
		END 
	FETCH NEXT FROM C_PEK_KEG_X1 INTO @VLC_KD_PEKERJAAN,@VLC_KD_KEGIATAN
	END	
		CLOSE C_PEK_KEG_X1
		DEALLOCATE C_PEK_KEG_X1
IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
END
ELSE
BEGIN
	COMMIT TRANSACTION
END  
END
