USE DBPAJAK 
GO
IF EXISTS(SELECT 1 FROM sys.procedures
          WHERE Name = 'DBKB_MAT_ADJUSTMENT')
BEGIN
    DROP PROC DBKB_MAT_ADJUSTMENT
END
GO
create PROCEDURE DBKB_MAT_ADJUSTMENT
@VLC_MASUKAN_TAHUN nvarchar(4)
AS
BEGIN
	DECLARE C_DBKB_MATERIAL CURSOR FOR
	SELECT KD_PEKERJAAN,KD_KEGIATAN,NILAI_DBKB_MATERIAL FROM  DBKB_MATERIAL
	WHERE  KD_PROPINSI       = '12' AND
		   KD_DATI2          = '12' AND
		   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN

	DECLARE @VLC_KD_PEK      NVARCHAR(2),
	@VLC_KD_KEG              NVARCHAR(2),
	@VLN_NILAI_DBKB_MATERIAL FLOAT,
	@VLN_ADJ_MTRL1           FLOAT,
	@VLN_ADJ_MTRL2           FLOAT,
	@VLN_2104                FLOAT,
	@VLN_2105                FLOAT,
	@VLN_2103                FLOAT,
	@VLN_2102                FLOAT,
	@VLN_2102_ADJ2           FLOAT,
	@VLN_2103_ADJ2           FLOAT,
	@VLN_210405              FLOAT,
	@VLN_ADJ_MTRL1_2102      FLOAT,
	@VLN_ADJ_MTRL1_2103      FLOAT

	OPEN C_DBKB_MATERIAL
	FETCH C_DBKB_MATERIAL INTO @VLC_KD_PEK, @VLC_KD_KEG, @VLN_NILAI_DBKB_MATERIAL
	WHILE @@FETCH_STATUS=0
	BEGIN
		SELECT @VLN_ADJ_MTRL1=D.PCT_ADJ_MTRL_1 FROM  ADJ_MATERIAL D WHERE  D.KD_PEKERJAAN =@VLC_KD_PEK AND D.KD_KEGIATAN  = @VLC_KD_KEG
		IF @VLN_ADJ_MTRL1 IS NULL
		BEGIN
	   		SET @VLN_ADJ_MTRL1 = 1
		END
	  	SELECT @VLN_ADJ_MTRL2=PCT_ADJ_MTRL_2 FROM ADJ_MATERIAL WHERE KD_PEKERJAAN = @VLC_KD_PEK AND KD_KEGIATAN  = @VLC_KD_KEG
		IF @VLN_ADJ_MTRL2 IS NULL
		BEGIN
			SET @VLN_ADJ_MTRL2 = 1
		END
		IF @VLC_KD_PEK = '21' AND @VLC_KD_KEG = '02' 
		BEGIN
			SET @VLN_2102_ADJ2 = (@VLN_NILAI_DBKB_MATERIAL * @VLN_ADJ_MTRL2)
		END 
		IF @VLC_KD_PEK = '21' AND @VLC_KD_KEG = '03' 
		BEGIN
			SET @VLN_2103_ADJ2 = (@VLN_NILAI_DBKB_MATERIAL * @VLN_ADJ_MTRL2)
		END 
		
		SET @VLN_NILAI_DBKB_MATERIAL =(@VLN_NILAI_DBKB_MATERIAL) * (@VLN_ADJ_MTRL1 * @VLN_ADJ_MTRL2)

		IF (@VLC_KD_PEK = '21' AND @VLC_KD_KEG = '04') OR (@VLC_KD_PEK = '21' AND @VLC_KD_KEG = '05') 
		BEGIN
			SET @VLN_NILAI_DBKB_MATERIAL = @VLN_NILAI_DBKB_MATERIAL
		END
		ELSE
		BEGIN
			SET  @VLN_NILAI_DBKB_MATERIAL = ROUND(@VLN_NILAI_DBKB_MATERIAL,0)
		END 

	  		UPDATE DBKB_MATERIAL SET    NILAI_DBKB_MATERIAL = @VLN_NILAI_DBKB_MATERIAL
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN  AND
				   KD_PEKERJAAN      = @VLC_KD_PEK         AND
		 		   KD_KEGIATAN       = @VLC_KD_KEG

		FETCH NEXT FROM C_DBKB_MATERIAL INTO @VLC_KD_PEK, @VLC_KD_KEG, @VLN_NILAI_DBKB_MATERIAL	
	END
		CLOSE C_DBKB_MATERIAL
		DEALLOCATE C_DBKB_MATERIAL
--END
		-- PENGHAPUSAN KODE '2104' DAN '2105' SERTA DIPERGUNAKAN UNTUK MENGHITUNG
		-- KODE '2102' DAN '2103'
		BEGIN

			SELECT @VLN_2104=NILAI_DBKB_MATERIAL FROM   DBKB_MATERIAL
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
				   KD_KEGIATAN       = '04'

			SELECT @VLN_2105=NILAI_DBKB_MATERIAL FROM   DBKB_MATERIAL
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
				   KD_KEGIATAN       = '05'

			
				SELECT @VLN_ADJ_MTRL1_2102=D.PCT_ADJ_MTRL_1 FROM   ADJ_MATERIAL D
				WHERE  D.KD_PEKERJAAN = '21' AND
			   		   D.KD_KEGIATAN  = '02'
				IF @VLN_ADJ_MTRL1_2102 IS NULL
				BEGIN
	   			   SET @VLN_ADJ_MTRL1_2102 = 1
				END

			
				SELECT @VLN_ADJ_MTRL1_2103=D.PCT_ADJ_MTRL_1 FROM   ADJ_MATERIAL D
				WHERE  D.KD_PEKERJAAN = '21' AND
			   		   D.KD_KEGIATAN  = '03'
--			EXCEPTION
--				WHEN NO_DATA_FOUND THEN
				IF @VLN_ADJ_MTRL1_2103 IS NULL 
				BEGIN
	   			   SET @VLN_ADJ_MTRL1_2103 = 1
				END

				SET @VLN_210405 = (@VLN_2104 + @VLN_2105 ) * 2 * 1.38

				SET @VLN_2102   = (@VLN_2102_ADJ2 + @VLN_2105) * @VLN_ADJ_MTRL1_2102

				SET @VLN_2103   = (@VLN_2103_ADJ2 + @VLN_210405) * @VLN_ADJ_MTRL1_2103


			UPDATE DBKB_MATERIAL SET    NILAI_DBKB_MATERIAL = ROUND(@VLN_2103,0)
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
				   KD_KEGIATAN       = '03'

			UPDATE DBKB_MATERIAL SET NILAI_DBKB_MATERIAL = ROUND(@VLN_2102,0)
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
		  		   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
				   KD_KEGIATAN       = '02'

			DELETE FROM DBKB_MATERIAL
			WHERE  KD_PROPINSI       = '12' AND
		  		   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
		  		   KD_KEGIATAN       = '04'

			DELETE FROM DBKB_MATERIAL
			WHERE  KD_PROPINSI       = '12' AND
				   KD_DATI2          = '12' AND
				   THN_DBKB_MATERIAL = @VLC_MASUKAN_TAHUN AND
				   KD_PEKERJAAN      = '21'              AND
				   KD_KEGIATAN       = '05'
		END
IF @@ERROR<>0
BEGIN
	ROLLBACK TRANSACTION
END
ELSE
BEGIN
	COMMIT TRANSACTION
END  
END
